
ALTER TABLE dbo.books
DROP CONSTRAINT UKkibbepcitr0a3cpk3rfr7nihn;


ALTER TABLE dbo.books ALTER COLUMN title NVARCHAR(255) NOT NULL;
ALTER TABLE dbo.books ALTER COLUMN author NVARCHAR(255) NOT NULL;
ALTER TABLE dbo.books ALTER COLUMN publisher NVARCHAR(255) NOT NULL;
ALTER TABLE dbo.books ALTER COLUMN isbn NVARCHAR(100) NOT NULL;
ALTER TABLE dbo.books ALTER COLUMN category NVARCHAR(255) NULL;
ALTER TABLE dbo.books ALTER COLUMN description NVARCHAR(MAX) NULL;


ALTER TABLE dbo.books
    ADD CONSTRAINT UKkibbepcitr0a3cpk3rfr7nihn UNIQUE(isbn);